- name: Setup dev environment
  hosts: local_dev
  roles:
    - role: fzf
      tags:
        - fzf
    - role: git
      tags:
        - git
    - role: kubernetes
      tags:
        - kubernetes
    - role: system
      tags:
        - system
    - role: tmux
      tags:
        - tmux
    - role: vim
      tags:
        - vim
    - role: zsh
      tags:
        - zsh
