- name: Install zsh for Ubuntu
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh for MacOS
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_distribution == "MacOSX"

- name: Check if .zshrc exist
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME ~ '/.zshrc' }}"
  register: zshrc

- name: Back up .zshrc
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME ~ '/.zshrc'}}"
    dest: "{{ ansible_env.HOME ~ '/.zshrc.bak'}}"
    mode: u=rw,g=r,o=r
  when: zshrc.stat.exists

- name: Copy .zshrc from template
  ansible.builtin.template:
    src: ".zshrc.j2"
    dest: "{{ ansible_env.HOME ~ '/.zshrc'}}"
    mode: u=rw,g=r,o=r

- name: Copy .dir_colors from template
  ansible.builtin.template:
    src: ".dir_colors.j2"
    dest: "{{ ansible_env.HOME ~ '/.dir_colors' }}"
    mode: u=rw,g=r,o=r
  when: ansible_distribution == "Ubuntu"

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}" # ansible magic variable
    shell: /bin/zsh

- name: Install zsh plugins
  ansible.builtin.git:
    repo: "{{ 'https://github.com/zsh-users/' ~ item }}"
    version: master
    dest: "{{ ansible_env.HOME ~ '/.zsh/' ~ item }}"
  loop:
    - zsh-autosuggestions
    - zsh-syntax-highlighting
