- name: Install fzf for Ubuntu
  become: true
  ansible.builtin.apt:
    name: fzf
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install fzf for MacOS
  community.general.homebrew:
    name: fzf
    state: present
  when: ansible_distribution == "MacOSX"

- name: Update config file
  ansible.builtin.include_role:
    name: shared_tasks
    tasks_from: copy_from_template
  vars:
    shared_tasks_target_dir: "{{ ansible_env.HOME ~ '/.fzf' }}"
    shared_tasks_file: ".fzfrc"
    shared_tasks_backup: true
