- name: Install git for Ubuntu
  become: true
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install git for MacOS
  community.general.homebrew:
    name: git
    state: present
  when: ansible_distribution == "MacOSX"

- name: Update config file
  ansible.builtin.include_role:
    name: shared_tasks
    tasks_from: copy_from_template
  vars:
    shared_tasks_target_dir: "{{ ansible_env.HOME }}"
    shared_tasks_file: .gitconfig
    shared_tasks_backup: true
