- name: Install git for Ubuntu
  become: true
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install git for MacOS
  community.general.homebrew:
    name: git
    state: present
  when: ansible_distribution == "MacOSX"

- name: Check if .gitconfig exist
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME ~ '/.gitconfig' }}"
  register: gitconfig

- name: Back up .gitconfig
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME ~ '/.gitconfig' }}"
    dest: "{{ ansible_env.HOME ~ '/.gitconfig.bak' }}"
    mode: u=rw,g=r,o=r
  when: gitconfig.stat.exists

- name: Make sure .gitconfig is up to date
  ansible.builtin.template:
    src: ".gitconfig.j2"
    dest: "{{ ansible_env.HOME ~ '/.gitconfig' }}"
    mode: u=rw,g=r,o=r
