# Install from release binaries, as this is the recommended way
- name: Download and install binary
  ansible.builtin.include_role:
    name: shared_tasks
    tasks_from: install_from_binary
  vars:
    shared_tasks_binary_url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}"
    shared_tasks_binary_download: "kind-{{ kubernetes_system }}-{{ kubernetes_arch }}"
    shared_tasks_binary_name: "kind"
    shared_tasks_binary_checksum_extension: sha256sum
