- name: Get the version information of the latest kubectl release
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/stable.txt"
    return_content: true
  register: kubctl_get_latest_version

- name: Ensure the version variable is set
  ansible.builtin.set_fact:
    kubectl_version: "{{ kubctl_get_latest_version.content }}"

- name: Download and install binary
  ansible.builtin.include_role:
    name: shared_tasks
    tasks_from: install_from_binary
  vars:
    shared_tasks_binary_url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/{{ kubernetes_system }}/{{ kubernetes_arch }}"
    shared_tasks_binary_download: "kubectl"
    shared_tasks_binary_name: "kubectl"
