- name: Install tmux for Ubuntu
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install tmux for MacOS
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_distribution == "MacOSX"

- name: Check if .tmux.conf exist
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME ~ '/.tmux.conf' }}"
  register: tmuxconf

- name: Back up .tmux.conf
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME ~ '/.tmux.conf' }}"
    dest: "{{ ansible_env.HOME ~ '/.tmux.conf.bak' }}"
    mode: u=rw,g=r,o=r
  when: tmuxconf.stat.exists

- name: Copy .tmux.conf from templates
  ansible.builtin.template:
    src: ".tmux.conf.j2"
    dest: "{{ ansible_env.HOME ~ '/.tmux.conf' }}"
    mode: u=rw,g=r,o=r

- name: Copy setup_tmux from files
  ansible.builtin.copy:
    src: "setup_session.sh"
    dest: "{{ ansible_env.HOME ~ '/setup_session.sh' }}"
    mode: u=rwx,g=rwx,o=x
  tags: additional
