- name: Install tmux for Ubuntu
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install tmux for MacOS
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_distribution == "MacOSX"

- name: Update config file
  ansible.builtin.include_role:
    name: shared_tasks
    tasks_from: copy_from_template
  vars:
    shared_tasks_target_dir: "{{ ansible_env.HOME ~ '/.tmux' }}"
    shared_tasks_file: .tmux.conf
    shared_tasks_backup: true

- name: Copy setup_session.sh from files
  ansible.builtin.copy:
    src: "setup_session.sh"
    dest: "{{ ansible_env.HOME ~ '/setup_session.sh' }}"
    mode: u=rwx,g=rwx,o=x
  tags: additional
